src/Entity/Formation.php
<?php
namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[ORM\Table(name: 'formations')]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    #[ORM\ManyToOne(targetEntity: Formateur::class, inversedBy: 'formations')]
    #[ORM\JoinColumn(name: 'formateur_id', referencedColumnName: 'id')]
    private ?Formateur $formateur = null;

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): self
    {
        $this->formateur = $formateur;
        return $this;
    }

    #[ORM\Column(type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(message: 'Le titre est obligatoire.')]
    #[Assert\Length(max: 255, maxMessage: 'Le titre ne doit pas dépasser 255 caractères.')]
    private ?string $title = null;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    // #[Assert\NotBlank(message: 'The image is required.')]
    private ?string $image = null;

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;
        return $this;
    }

    #[ORM\Column(type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(message: 'La description est obligatoire.')]
    #[Assert\Length(max: 255, maxMessage: 'La description ne doit pas dépasser 255 caractères.')]
    private ?string $description = null;

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }

    #[ORM\Column(type: 'boolean', nullable: false)]
    private ?bool $is_online = null;

    public function is_online(): ?bool
    {
        return $this->is_online;
    }

    public function setIs_online(bool $is_online): self
    {
        $this->is_online = $is_online;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $place = null;

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;
        return $this;
    }

    #[ORM\Column(type: 'decimal', nullable: true)]
    // #[Assert\NotNull(message: 'Latitude is required.')]
    #[Assert\Type(type: 'float', message: 'La latitude doit être un nombre décimal.')]
    private ?float $lat = null;

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(?float $lat): self
    {
        $this->lat = $lat;
        return $this;
    }

    #[ORM\Column(type: 'decimal', nullable: true)]
    // #[Assert\NotNull(message: 'Longitude is required.')]
    #[Assert\Type(type: 'float', message: 'La longitude doit être un nombre décimal.')]
    private ?float $lng = null;

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(?float $lng): self
    {
        $this->lng = $lng;
        return $this;
    }

    #[ORM\Column(type: 'boolean', nullable: false)]
    private ?bool $available_for_employee = null;

    public function isAvailable_for_employee(): ?bool
    {
        return $this->available_for_employee;
    }

    public function setAvailable_for_employee(bool $available_for_employee): self
    {
        $this->available_for_employee = $available_for_employee;
        return $this;
    }

    #[ORM\Column(type: 'boolean', nullable: false)]
    private ?bool $available_for_intern = null;

    public function isAvailable_for_intern(): ?bool
    {
        return $this->available_for_intern;
    }

    public function setAvailable_for_intern(bool $available_for_intern): self
    {
        $this->available_for_intern = $available_for_intern;
        return $this;
    }

    #[ORM\Column(type: 'datetime', nullable: true)]
    #[Assert\NotNull(message: 'La date de début est obligatoire.')]
    #[Assert\Type(\DateTimeInterface::class, message: 'La date de début doit être une date et heure valide.')]
    #[Assert\GreaterThanOrEqual(value: "now", message: "La date de début doit être supérieure ou égale à la date et heure actuelle.")]
    private ?\DateTimeInterface $start_date = null;

    public function getStart_date(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStart_date(\DateTimeInterface $start_date) : self
    {
        $this->start_date = $start_date;
        return $this;
    }

    #[ORM\Column(type: 'datetime', nullable: true)]
    #[Assert\NotNull(message: 'La date de fin est obligatoire.')]
    #[Assert\Type(\DateTimeInterface::class, message: 'La date de fin doit être une date et heure valide.')]
    #[Assert\Expression(
        "this.getEndDate() >= this.getStartDate()",
        message: "End date must be after start date."
    )]
    private ?\DateTimeInterface $end_date = null;

    public function getEnd_date(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEnd_date( ? \DateTimeInterface $end_date) : self
    {
        $this->end_date = $end_date;
        return $this;
    }

    #[ORM\Column(type : 'decimal', nullable: true)]
    #[Assert\NotNull(message: 'Le prix est obligatoire.')]
    #[Assert\Type(type: 'float', message: 'Le prix doit être un nombre décimal.')]
    #[Assert\GreaterThanOrEqual(value: 0, message: 'Le prix doit être supérieur ou égal à zéro.')]
    private ?float $price = null;

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;
        return $this;
    }

    #[ORM\OneToMany(targetEntity: Quiz::class, mappedBy: 'formation')]
    private Collection $quizs;

    /**
     * @return Collection<int, Quiz>
     */
    public function getQuizs(): Collection
    {
        if (! $this->quizs instanceof Collection) {
            $this->quizs = new ArrayCollection();
        }
        return $this->quizs;
    }

    public function addQuiz(Quiz $quiz): self
    {
        if (! $this->getQuizs()->contains($quiz)) {
            $this->getQuizs()->add($quiz);
        }
        return $this;
    }

    public function removeQuiz(Quiz $quiz): self
    {
        $this->getQuizs()->removeElement($quiz);
        return $this;
    }

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'formations')]
    #[ORM\JoinTable(
        name: 'formation_participation',
        joinColumns: [
            new ORM\JoinColumn(name: 'formation_id', referencedColumnName: 'id'),
        ],
        inverseJoinColumns: [
            new ORM\JoinColumn(name: 'employe_id', referencedColumnName: 'id'),
        ]
    )]
    private Collection $users;

    public function __construct()
    {
        $this->quizs = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getUsers(): Collection
    {
        if (! $this->users instanceof Collection) {
            $this->users = new ArrayCollection();
        }
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (! $this->getUsers()->contains($user)) {
            $this->getUsers()->add($user);
        }
        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->getUsers()->removeElement($user);
        return $this;
    }

    public function isOnline(): ?bool
    {
        return $this->is_online;
    }

    public function setIsOnline(bool $is_online): static
    {
        $this->is_online = $is_online;

        return $this;
    }

    public function isAvailableForEmployee(): ?bool
    {
        return $this->available_for_employee;
    }

    public function setAvailableForEmployee(bool $available_for_employee): static
    {
        $this->available_for_employee = $available_for_employee;

        return $this;
    }

    public function isAvailableForIntern(): ?bool
    {
        return $this->available_for_intern;
    }

    public function setAvailableForIntern(bool $available_for_intern): static
    {
        $this->available_for_intern = $available_for_intern;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate( ? \DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate( ? \DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

}

src/Form/FormationType.php
<?php
namespace App\Form;

use App\Entity\Formateur;
use App\Entity\Formation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            // ->add('image')
            ->add('description')
            ->add('is_online')
            ->add('place')
            ->add('lat', NumberType::class)
            ->add('lng', NumberType::class)
            ->add('available_for_employee')
            ->add('available_for_intern')
            ->add('start_date', null, [
                'widget'     => 'single_text',
                'empty_data' => '',
                'required'   => true,
            ])
            ->add('end_date', null, [
                'widget'     => 'single_text',
                'empty_data' => '',
            ])
            ->add('price', NumberType::class)
            ->add('formateur', EntityType::class, [
                'class'        => Formateur::class,
                'choice_label' => function (Formateur $formateur) {
                    return $formateur->getFirstName() . ' ' . $formateur->getLastName();
                },
            ])
            // ->add('employes', EntityType::class, [
            //     'class'        => Employe::class,
            //     'choice_label' => 'id',
            //     'multiple'     => true,
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php
namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/backoffice/formations')]
final class FormationController extends AbstractController
{
    #[Route(name: 'app_formations_index', methods: ['GET'])]
    public function index(Request $request, FormationRepository $formationRepository, PaginatorInterface $paginator): Response
    {
        $type = $request->query->get('type');

        if ($type == 'free') {
            $query = $formationRepository->createQueryBuilder('f')
                ->where('f.price = 0')
                ->getQuery();
        } elseif ($type == 'paid') {
            $query = $formationRepository->findPaidFormations();
        } else {
            $query = $formationRepository->createQueryBuilder('f')
                ->getQuery();
        }

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            7
        );

        return $this->render('formations/index.html.twig', [
            'formations' => $pagination, // Now paginated
            'type'       => $type,
        ]);
    }

    #[Route('/new', name: 'app_formations_new', methods: ['GET', 'POST'])]
    public function new (Request $request, EntityManagerInterface $entityManager): Response
    {
        $formation = new Formation();
        $form      = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $request->files->get('image');

            if ($file == null) {
                $this->addFlash('danger', 'Choisir une image');
                return $this->render('formations/new.html.twig', [
                    'formation' => $formation,
                    'form'      => $form,
                ]);
            }

            $imageContent = file_get_contents($file->getPathname());

            $apiKey = $_ENV['IMG_BB_API_KEY'];
            $url    = 'https://api.imgbb.com/1/upload?key=' . $apiKey;
            $data   = [
                'image' => base64_encode($imageContent),
            ];

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            $response = curl_exec($ch);
            curl_close($ch);

            $responseData = json_decode($response, true);
            if (isset($responseData['data']['url'])) {
                $imageUrl = $responseData['data']['url'];
                $formation->setImage($imageUrl);
            }

            $entityManager->persist($formation);
            $entityManager->flush();

            $this->addFlash('success', 'The training has been created successfully.');

            return $this->redirectToRoute('app_formations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('formations/new.html.twig', [
            'formation' => $formation,
            'form'      => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formations_show', methods: ['GET'])]
    public function show(Formation $formation): Response
    {
        return $this->render('formations/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $request->files->get('image');

            if ($file != null) {
                $imageContent = file_get_contents($file->getPathname());

                $apiKey = $_ENV['IMG_BB_API_KEY'];
                $url    = 'https://api.imgbb.com/1/upload?key=' . $apiKey;
                $data   = [
                    'image' => base64_encode($imageContent),
                ];

                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_POST, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                $response = curl_exec($ch);
                curl_close($ch);

                $responseData = json_decode($response, true);
                if (isset($responseData['data']['url'])) {
                    $imageUrl = $responseData['data']['url'];
                    $formation->setImage($imageUrl);
                }
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_formations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('formations/edit.html.twig', [
            'formation' => $formation,
            'form'      => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formations_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $formation->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        $this->addFlash('success', 'The training has been deleted successfully.');

        return $this->redirectToRoute('app_formations_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formations/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_controller_v2_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formations/edit.html.twig
{% extends 'back_office.html.twig' %}

{% block title %}Modifier Une Formation
{% endblock %}

{% block css %}
	{{ parent() }}

	<style>
		#map {
			height: 500px;
			width: 100%;
			margin-top: 10px;
		}
	</style>
{% endblock %}


{% block body %}
	<h1>Modifier Une Formation</h1>

	{{ include('formations/_form.html.twig', {'button_label': 'Modifier'}) }}

{% endblock %}

{% block cjs %}
	<script>

		$(document).ready(function () {

$('#formation_is_online').bootstrapToggle();
if ($('#formation_is_online').prop('checked')) {
$('#f_place').hide();
$('#f_lat_lng').hide();
}
$('#formation_is_online').change(function () {
if ($(this).prop('checked')) {
$('#f_place').hide();
$('#f_lat_lng').hide();
} else {
$('#f_place').show();
$('#f_lat_lng').show();
}
});

});
	</script>

	<script></script>

	<script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&libraries=places&callback=initMap" async defer></script>


	<script>
		let map,
marker,
autocomplete;

function initMap() { // Initial map center
const initialPosition = {
lat: {{ formation.lat }},
lng: {{ formation.lng }}
};

// Initialize the map
map = new google.maps.Map(document.getElementById("map"), {
center: initialPosition,
zoom: 13
});

// Add initial marker
marker = new google.maps.Marker({position: initialPosition, map: map, draggable: false});

// Initialize autocomplete
const input = document.getElementById("formation_place");
autocomplete = new google.maps.places.Autocomplete(input);
autocomplete.bindTo("bounds", map);

// Listen for place changes in autocomplete
autocomplete.addListener("place_changed", () => {
const place = autocomplete.getPlace();
if (! place.geometry) {
alert("No details available for the selected place.");
return;
}

// Remove the previous marker
marker.setMap(null);

// Update map center and zoom
map.setCenter(place.geometry.location);
map.setZoom(15);

// Add a new marker at the selected place
marker = new google.maps.Marker({position: place.geometry.location, map: map, draggable: false});

// Get and set the latitude and longitude
const lat = place.geometry.location.lat();
const lng = place.geometry.location.lng();
console.log("Selected coordinates:", lat, lng);

document.getElementById("formation_lat").value = lat;
document.getElementById("formation_lng").value = lng;
});
}

window.onload = initMap;
	</script>

{% endblock %}

templates/formations/formation_meet.html.twig
{% extends 'front_office.html.twig' %}

{% block title %}
	Training List
{% endblock %}

{% block body %}
	<main>


		<section class="pt-5">
			<div class="container">

				<div
					class="row g-4 g-sm-5">
					<!-- Main content START -->
					<div
						class="col-xl-12 mb-4 mb-sm-0">


						<!-- Personal info START -->
						<div
							class="card card-body shadow p-4">
							<!-- Title -->
							{% if app.session.flashBag.has('error') %}
								<div class="alert alert-danger" role="alert">
									{{ app.session.flashBag.get('error')|first }}
								</div>
							{% endif %}
							<h5 class="mb-1">{{ formation.title }}</h5>

							<div id="meet"></div>

						</div>
						<!-- Personal info END -->
					</div>
					<!-- Main content END -->


				</div>
				<!-- Right sidebar END -->

			</div>
			<!-- Row END -->
		</div>
	</section>
	<!-- =======================
																																																					Page content END -->

</main>{% endblock %}{% block js %}
{{ parent() }}
<script src='https://meet.jit.si/external_api.js'></script>
<script>
	const domain = 'meet.jit.si/hrconnect';
const options = {
roomName: '{{ formation.title }}',
width: '100%',
height: 700,
parentNode: document.querySelector('#meet'),
userInfo: {
email: 'haithemdridiweb@gmail.com',
'displayName': "Haythem Dridi"
},
configOverwrite: {
defaultLanguage: 'fr'
}
};
const api = new JitsiMeetExternalAPI(domain, options);
</script></script>{% endblock %}

templates/formations/index.html.twig
{% extends 'back_office.html.twig' %}

{% block title %}
	Liste des formations
{% endblock %}

{% block body %}
	<div class="row">
		<div class="col-xl-12 col-sm-12 col-12">
			<div class="breadcrumb-path mb-4">
				<ul class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="index.html"><img src="{{ asset('assets/img/')}}" class="mr-2" alt="breadcrumb"/>Home</a>
					</li>
					<li class="breadcrumb-item active">
						Liste des formations
					</li>
				</ul>
				<h3>Questions</h3>
			</div>
		</div>
		<div class="col-xl-12 col-sm-12 col-12 mb-4">
			<div class="head-link-set">
				<ul>
					<li>
						<a class="{{ app.request.query.get('type') is null ? 'active' : '' }}" href="{{ path('app_formations_index') }}">Toutes les formations</a>
					</li>
					<li>
						<a class="{{ app.request.query.get('type') == 'free' ? 'active' : '' }}" href="{{ path('app_formations_index') }}?type=free">Formations Grauites</a>
					</li>
					<li>
						<a class="{{ app.request.query.get('type') == 'paid' ? 'active' : '' }}" href="{{ path('app_formations_index') }}?type=paid">Formations Payantes</a>
					</li>
				</ul>
				<a class="btn-add" href="{{ url('app_formations_new') }}">
					<i data-feather="plus"></i>
					Ajouter une formation
				</a>
			</div>
		</div>
		<div class="col-xl-12 col-sm-12 col-12 mb-4">
			<div class="card">
				<div class="table-heading">
					<h2>Liste des formations</h2>
				</div>
				<div class="table-responsive">
					<table class="table  custom-table no-footer">
						<thead>
							<tr>
								<th>Id</th>
								<th>Titre</th>
								<th>Lieu</th>
								<th>Prix</th>
								<th>Disponible pour</th>
								<th>Date de début</th>
								<th>Date de fin</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for formation in formations %}
								<tr>
									<td>{{ formation.id }}</td>
									<td>
										<img src="{{ asset(formation.image) }}" alt="profile" class="img-table" width="50px" height="50px"/>
										<label>{{ formation.title }}</label>
									</td>
									<td>
										{% if formation.place is empty %}
											<label class="action_label">
												<i class="fas fa-globe"></i>
												ONLINE
											</label>
										{% else %}
											{{ formation.place }}
										{% endif %}
									</td>
									<td>
										{% if formation.price == 0 %}
											<label class="action_label">
												FREE
											</label>
										{% else %}
											{{ formation.price }}
											TND
										{% endif %}
									</td>
									<td>
										{% if formation.availableForEmployee %}
											<label class="action_label">
												Employées
											</label>
										{% endif %}
										{% if formation.availableForIntern %}
											<label class="action_label2">
												Interns
											</label>
										{% endif %}
									</td>
									<td>{{ formation.startDate ? formation.startDate|date('Y-m-d H:i:s') : '' }}</td>
									<td>{{ formation.endDate ? formation.endDate|date('Y-m-d H:i:s') : '' }}</td>
									<td>
										<form method="post" action="{{ path('app_formations_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
											<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
											<a class="btn btn-success btn-sm" href="{{ path('app_formations_show', {'id': formation.id}) }}">
												<i class="fas fa-eye"></i>
												Affichier
											</a>
											<a class="btn btn-primary btn-sm" href="{{ path('app_quiz_index', {'fid': formation.id}) }}">
												<i class="fas fa-eye"></i>
												Quiz
											</a>
											<a class="btn btn-success btn-sm" href="{{ path('app_formations_edit', {'id': formation.id}) }}">
												<i class="fas fa-edit"></i>
												Modifier
											</a>
											<button class="btn btn-danger btn-sm">
												<i class="fas fa-trash"></i>
												Supprimer
											</button>
										</form>

									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>

					<center>
						<div class="navigation">
							{{ knp_pagination_render(formations) }}
						</div>
					</center>

				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/formations/payment_success_email.html.twig
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Confirmation de Paiement</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<style>
			/* Simple Bootstrap-like inline styles */
			body {
				font-family: Arial, sans-serif;
				background-color: #f8f9fa;
				padding: 20px;
				margin: 0;
			}
			.container {
				background-color: #ffffff;
				padding: 30px;
				border-radius: 8px;
				box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
				max-width: 600px;
				margin: 20px auto;
			}
			.btn {
				display: inline-block;
				padding: 10px 20px;
				margin-top: 20px;
				font-size: 16px;
				color: #ffffff;
				background-color: #0d6efd;
				text-decoration: none;
				border-radius: 5px;
			}
			h1 {
				color: #0d6efd;
			}
		</style>
	</head>
	<body>
		<div class="container">
			<h1>Confirmation de Paiement</h1>
			<p>Bonjour
				{{ name }},</p>

			<p>Nous vous confirmons la réception de votre paiement pour la formation
				<strong>{{ formation_name }}</strong>.</p>

			<p>Merci de votre confiance. Nous sommes impatients de vous accompagner tout au long de votre parcours de formation.</p>

			<a href="{{ formation_link }}" class="btn">Accéder à la formation</a>

			<p style="margin-top: 30px;">Cordialement,<br>L'équipe Formation</p>
		</div>
	</body>
</html>

templates/formations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation
{% endblock %}

{% block body %}
	<h1>Formation</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ formation.id }}</td>
			</tr>
			<tr>
				<th>Title</th>
				<td>{{ formation.title }}</td>
			</tr>
			<tr>
				<th>Image</th>
				<td>{{ formation.image }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ formation.description }}</td>
			</tr>
			<tr>
				<th>Is_online</th>
				<td>{{ formation.isOnline ? 'Yes' : 'No' }}</td>
			</tr>
			<tr>
				<th>Place</th>
				<td>{{ formation.place }}</td>
			</tr>
			<tr>
				<th>Lat</th>
				<td>{{ formation.lat }}</td>
			</tr>
			<tr>
				<th>Lng</th>
				<td>{{ formation.lng }}</td>
			</tr>
			<tr>
				<th>Available_for_employee</th>
				<td>{{ formation.availableForEmployee ? 'Yes' : 'No' }}</td>
			</tr>
			<tr>
				<th>Available_for_intern</th>
				<td>{{ formation.availableForIntern ? 'Yes' : 'No' }}</td>
			</tr>
			<tr>
				<th>Start_date</th>
				<td>{{ formation.startDate ? formation.startDate|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>End_date</th>
				<td>{{ formation.endDate ? formation.endDate|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Price</th>
				<td>{{ formation.price }}</td>
			</tr>
		</tbody>
	</table>

{% endblock %}